apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: kafka-app

resources:
  - kafka-connect.yaml
  - my-sql-credentials.yaml
  - kafka-connector.yaml
